# Generated by Django 4.0.5 on 2022-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ncm', models.IntegerField(verbose_name='NCM')),
                ('desc', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ii', models.FloatField(verbose_name='Imposto de Importação')),
                ('ipi', models.FloatField(verbose_name='Imposto sobre Produto Industrializado')),
                ('pis', models.FloatField(verbose_name='PIS')),
                ('cofins', models.FloatField(verbose_name='COFINS')),
                ('icms', models.FloatField(verbose_name='ICMS')),
                ('imagem', models.ImageField(null=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
    ]
